spring:
  application:
    name: hospital-management-system
  datasource:
    #LOCAL DB
    url: jdbc:mysql://localhost:3306/hospital_management_system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

    #REMOTE DB
#    url: jdbc:mysql://192.168.56.45:3306/hospital_management_server
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: aman
#    password: pass@123


  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    rest:
      base-path: /api
